import { TextStyle, ViewStyle } from 'react-native';

export const frontdeskTheme = {
  colors: {
    background: '#F6F0E7',
    surface: '#FFFEFB',
    surfaceMuted: '#FCF7EF',
    border: '#E2D2BE',
    borderSoft: '#EADFD1',
    textPrimary: '#3A2A1B',
    textSecondary: '#4D453B',
    textTertiary: '#6A5E4F',
    primary: '#6B3F1F',
    primaryPressed: '#5A351B',
    onPrimary: '#FFFFFF',
    dangerBg: '#FFF2EF',
    dangerBorder: '#D06C5F',
    dangerText: '#B3382B',
    warningBg: '#FFF8ED',
    warningBorder: '#E8CFA5',
    warningText: '#6F4D1B',
    successBg: '#E8F4E9',
    successText: '#2E6A3A',
    errorBg: '#F8E8E5',
    errorText: '#A33B2E',
    statusNewBg: '#FFF2D9',
    statusNewBorder: '#E8C891',
    statusAcceptedBg: '#EAF3FF',
    statusAcceptedBorder: '#BBD3F2',
    statusCancelledBg: '#FCEBE7',
    statusCancelledBorder: '#E9B8AD',
    statusNeutralBg: '#EEF1F5',
    statusNeutralBorder: '#CED7E3',
  },
  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    pill: 999,
  },
  typography: {
    titleLg: { fontSize: 26, lineHeight: 32, fontWeight: '800' as TextStyle['fontWeight'] },
    titleMd: { fontSize: 20, lineHeight: 26, fontWeight: '800' as TextStyle['fontWeight'] },
    section: { fontSize: 18, lineHeight: 24, fontWeight: '700' as TextStyle['fontWeight'] },
    body: { fontSize: 14, lineHeight: 20, fontWeight: '500' as TextStyle['fontWeight'] },
    bodyStrong: { fontSize: 15, lineHeight: 22, fontWeight: '700' as TextStyle['fontWeight'] },
    button: { fontSize: 14, lineHeight: 20, fontWeight: '700' as TextStyle['fontWeight'] },
    caption: { fontSize: 11, lineHeight: 14, fontWeight: '800' as TextStyle['fontWeight'] },
  },
  elevation: {
    card: {
      shadowColor: '#4C3921',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    } as ViewStyle,
    dock: {
      shadowColor: '#4C3921',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 3,
    } as ViewStyle,
  },
  touch: {
    min: 38,
    medium: 42,
    large: 46,
  },
} as const;

export const frontdeskTextAlign = {
  rtl: { textAlign: 'right' as const, writingDirection: 'rtl' as const, direction: 'rtl' as const },
  ltr: { textAlign: 'left' as const, writingDirection: 'ltr' as const, direction: 'ltr' as const },
};
